### ISSUE TITLE
Week 9 

### ISSUE THREAD

**Issue by mih9898** [mturchanov-matc-school-projects/ent-java-team-project-csv-parser-rest#2]
@pawaitemadisoncollege, team project as week9 exercise can be reviewed

**What were your key learning points/takeaways?**
- jersey, Jackson for parsing CSV  

**What challenged you?**
- the forked state farm project didn't want to work with jersey. Initially, it was a non-web app.  Even when the web framework was added via Intellij it didn't work. Apparently, jersey see some differences between maven-project from blank and project to which web framework was added

**What problems did you solve and what resources did you use to solve them?**
- jersey

**Comment by pawaitemadisoncollege** [comment]
@mih9898 This looks like a good start on the team project and good first cut at one resource/operation/response type.
